name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_sqlite
      - run: composer install --no-interaction --no-progress
      - run: composer cs
      - run: composer analyse
      - run: vendor/bin/phpunit
